linters:
  enable:
    - dogsled
    - errcheck
    - exhaustive
    - gocritic
    - gofmt
    - goimports
    - gosec
    - misspell
    - noctx
    - nolintlint
    - staticcheck
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - io.ReadAll
  goimports:
    local-prefixes: github.com/KooshaPari
  staticcheck:
    checks:
      - all
      - -SA1012
