name: cargo-machete
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push: { branches: [main], paths: ['Cargo.toml', '**/Cargo.toml'] }
  pull_request: { paths: ['Cargo.toml', '**/Cargo.toml'] }
  schedule: [{ cron: '47 6 * * 4' }]
  workflow_dispatch:
jobs:
  machete:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: bnjbvr/cargo-machete@964923f7ed1dd92870ed602ef8fbb2eac0eb51de
